// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protoMessages/clientKline.proto

package protoMessages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KlineServiceClient is the client API for KlineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KlineServiceClient interface {
	Kline(ctx context.Context, in *KlineRequest, opts ...grpc.CallOption) (*KlineResponce, error)
}

type klineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKlineServiceClient(cc grpc.ClientConnInterface) KlineServiceClient {
	return &klineServiceClient{cc}
}

func (c *klineServiceClient) Kline(ctx context.Context, in *KlineRequest, opts ...grpc.CallOption) (*KlineResponce, error) {
	out := new(KlineResponce)
	err := c.cc.Invoke(ctx, "/secondService.protoMessages.KlineService/Kline", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KlineServiceServer is the server API for KlineService service.
// All implementations must embed UnimplementedKlineServiceServer
// for forward compatibility
type KlineServiceServer interface {
	Kline(context.Context, *KlineRequest) (*KlineResponce, error)
	mustEmbedUnimplementedKlineServiceServer()
}

// UnimplementedKlineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKlineServiceServer struct {
}

func (UnimplementedKlineServiceServer) Kline(context.Context, *KlineRequest) (*KlineResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kline not implemented")
}
func (UnimplementedKlineServiceServer) mustEmbedUnimplementedKlineServiceServer() {}

// UnsafeKlineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KlineServiceServer will
// result in compilation errors.
type UnsafeKlineServiceServer interface {
	mustEmbedUnimplementedKlineServiceServer()
}

func RegisterKlineServiceServer(s grpc.ServiceRegistrar, srv KlineServiceServer) {
	s.RegisterService(&KlineService_ServiceDesc, srv)
}

func _KlineService_Kline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KlineServiceServer).Kline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/secondService.protoMessages.KlineService/Kline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KlineServiceServer).Kline(ctx, req.(*KlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KlineService_ServiceDesc is the grpc.ServiceDesc for KlineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KlineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "secondService.protoMessages.KlineService",
	HandlerType: (*KlineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Kline",
			Handler:    _KlineService_Kline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoMessages/clientKline.proto",
}
